### PR TITLE
Enable using PushSubscription with crossbeam_channel::Select

### PR DESCRIPTION
**Pull request by marjakm**
0.17.0 refactored Jetstream interface and I don't see how I can use `crossbeam_channel::Select` with `PushSubscription`. 

In previous versions, the `Consumer` contained an optional `Subscription`, that exposed `crossbeam_channel::Receiver` https://docs.rs/nats/0.16.0/nats/jetstream/struct.Consumer.html. 

`Receiver` was exposed in this pull request by me https://github.com/nats-io/nats.rs/pull/162

Not all Messages in `PushSubscription` are exposed to the library user currently:

```rust
    pub fn try_next(&self) -> Option<Message> {
        match self.0.messages.try_recv().ok() {
            Some(message) => {
                if self.preprocess(&message) {
                    return self.try_next();
                }
                Some(message)
            }
            None => None,
        }
    }

    fn preprocess(&self, message: &Message) -> bool {
        if message.is_flow_control() {
            message.respond(b"").ok();
            return true;
        }
        if message.is_idle_heartbeat() {
            return true;
        }
        false
    }

```

Because of that, I chose not to expose the Receiver and only added the ability to register to the Select.

### CODE REVIEW

**Comment by caspervonb** [comment]
Not very excited about exposing crossbeam_channel but I see the value, I'll discuss a bit offline with @Jarema and we'll get back to this soon.

Presumably, a real async client would make the problem go away as you'd get first class support for select! via streams (subscriptions would be streams).

**Comment by marjakm** [comment]
For me, a real async client would indeed make the access to crossbeam select unnecessary.

But some users may still want to use the sync client, and I think the interface for this lib currently makes the "fan-in" case a bit hard to handle. By that, I mean, the different subscriptions are not composable - you create different subscriptions one-by-one and have to handle them all separately, the lib does not provide any operations to join/select on multiple subscriptions at once.

My solution to this was to expose the crossbeam Receiver that is composable by using Select. The real async client would provide Streams, that are composable. Aside from exposing the implementation detail of crossbeam, the lib could implement its own composition, for example:

```rust
pub struct SubscriptionJoin {..}

impl Subcription { //
   fn join(self, other: Subscription) -> SubscriptionJoin {..}
}

impl SubscriptionJoin {
   pub fn next(&self) -> Option<Message> { .. } // internally does a crossbeam select
}
```

**Comment by marjakm** [comment]
But a custom composition is not the ideal case as it would only enable composition of objects in the this lib. Crossbeam Select and Future/Stream in async rust are composable in large as they are popular in the rust ecosystem.

**Comment by marjakm** [comment]
Rebased to latest main and added `complete_select_recv` function - `crossbeam` requires that you complete the recv through its `SelectedOperation::recv`

**Comment by caspervonb** [comment]
We've shipped an async client under async_nats, jetstream support for it is shipping really soon so I'll go ahead and close this without merge.

**Comment by Jarema** [comment]
@marjakm `async_nats` now supports JetStream, which allows for what you're requiring here.



Can we treat this one as stale and irrelevant and close it?

**Comment by caspervonb** [comment]
> @marjakm `async_nats` now supports JetStream, which allows for what you're requiring here.
> 
> Can we treat this one as stale and irrelevant and close it?

This came up in slack again recently, which is when I reopened it.

**Comment by Jarema** [comment]
As the sync client is deprecated now, I'm closing this one.

If there is anything missing in async client with similar scope, let us know and open a new issue.

**Pull request closed without merging**
