### PR TITLE
Keep error details when mapping errors

### PR DESCRIPTION
**Pull request by caspervonb**

### CODE REVIEW

**Review by Jarema — COMMENTED** [review]
@caspervonb I'm afraid that this will produce very cryptic errors not telling us quickly what exactly happened (which proto op failed).

Maybe do as you did, but wrap with additional info? `io::Error::new(ErrorKind::InvalidInput, format!("cannot convert server info: {}", err))`

**Comment by caspervonb** [comment]
> @caspervonb I'm afraid that this will produce very cryptic errors not telling us quickly what exactly happened (which proto op failed).
> 
> Maybe do as you did, but wrap with additional info? `io::Error::new(ErrorKind::InvalidInput, format!("cannot convert server info: {}", err))`

String is less useful than an error.
When we want to introduce more context we need additional error types.

**Comment by Jarema** [comment]
yeah, agree. Though loosing contect is not good either.
I think we should have that context.

**Review by Jarema — APPROVED** [review]
LGTM

**Pull request merged**
