### PR TITLE
Add compression option to kv

### PR DESCRIPTION
**Pull request by Jarema**
Signed-off-by: Tomasz Pietrek <tomasz@nats.io>

### CODE REVIEW

**Comment by Jarema** [comment]
relevant issue: https://github.com/nats-io/nats-architecture-and-design/issues/253

**Review by neilalexander — APPROVED** [review]

**Review by piotrpio — APPROVED** [review]
LGTM!

**Review by piotrpio — COMMENTED** [review]
Backtracking a bit - ADR specified compression for KV as a boolean flag, rather than allowing to pick up a specific compression algorithm - https://github.com/nats-io/nats-architecture-and-design/pull/252/files

We need to discuss and align this setting across all clients

**Comment by ripienaar** [comment]
For KV where the purpose is minimal API surface area and minimal choices - and maximal chance of having alternative backends a Boolean is best. 

We should make the right choice for users and not surface extra options where those will just complicate matters. 

That means today it’s s2 or nothing

**Comment by Jarema** [comment]
I need to think about it for a while. But I think agree. Will follow up.

**Pull request merged**
