### PR TITLE
Add const representation for standard header names

### PR DESCRIPTION
**Pull request by caspervonb**
Add const representation (an enum) for standard known header names.

Closes https://github.com/nats-io/nats.rs/issues/945

### CODE REVIEW

**Review by Jarema — CHANGES_REQUESTED** [review]
It looks ok, but I'm not happy about reintroducing `unsafe` block.
Wondering if we can get rid of it.

**Comment by caspervonb** [comment]
> It looks ok, but I'm not happy about reintroducing unsafe block.
> Wondering if we can get rid of it.

Can't really get rid of it.

**Comment by Jarema** [comment]
> Can't really get rid of it. It is safe tho, as the data is valid utf-8.

@caspervonb I agree it's safe, but as some of our contributors mentioned, people run checks and disallow libraries with unsafe blocks. That's my concern.

**Comment by caspervonb** [comment]
> @caspervonb I agree it's safe, but as some of our contributors mentioned, people run checks and disallow libraries with unsafe blocks. That's my concern.

I'm not particularly worried about invariants that are known to be safe.
Even basic std string operations contain unsafe blocks.

Difference between just having to call an unsafe function to achieve an operation that is safe for a certain condition and being clever with unsafe hacks are quite different imo.

**Review by Jarema — APPROVED** [review]
LGTM

**Pull request merged**
