### PR TITLE
Don't run options doctests

### PR DESCRIPTION
**Pull request by caspervonb**

### CODE REVIEW

**Comment by Jarema** [comment]
If we disabled those tests, I would prefer to actually test those options in actual tests ;).

**Comment by caspervonb** [comment]
Presumably you do?

**Comment by Jarema** [comment]
Flush interval and ping interval are not explicitly tested. Rest is.

**Comment by caspervonb** [comment]
Lets follow up with that (this wasn't providing any good coverage for it).

**Pull request merged**
