### PR TITLE
Release sync nats/v0.25.0

### PR DESCRIPTION
**Pull request by Jarema**
Signed-off-by: Tomasz Pietrek <tomasz@nats.io>

### CODE REVIEW

**Comment by paolobarbolini** [comment]
I hope they make a release soon for https://github.com/wasmCloud/nkeys/pull/31 so that we can include it.

**Comment by Jarema** [comment]
Oh, that is a good point @paolobarbolini 
Let me ping them :).

**Comment by Jarema** [comment]
Bumped the NKEYS in the sync client. Thank you @brooksmtownsend for a quick release! ❤️

**Comment by paolobarbolini** [comment]
You may also put `+deprecated` in the verdion

**Review by piotrpio — APPROVED** [review]
LGTM!

**Pull request merged**
