### PR TITLE
feat: allow parse message data as json

### PR DESCRIPTION
**Pull request by xoac**

### CODE REVIEW

**Comment by Jarema** [comment]
Thanks for your contribution @xoac !

Are you sure you wanted to update just the example?

Besides:
For any `nats` cli experience, I would stick to https://github.com/nats-io/natscli , which is a very powerful tool.

For any code-related work, I would use `async-nats` crate.

**Comment by xoac** [comment]
Hi @Jarema it works well and it's simpler CLI for testing than natscli. The code of rust version is shorter than the README.md of natscli and I don't need to install yet another language compiler. I just pushed PR because I wanted to print the json format of messages that I publish with `async-nats` ;)

> Are you sure you wanted to update just the example?

What else you want update here?

**Comment by Jarema** [comment]
> What else you want update here?

I meant that this is just a short example how library can be used :).

Just FYI - you don't need Go compiler to work with CLI, nor read much of the docs. it's the same `nats pub` and `nats sub`.
It's available as released binary and in some package managers.

As said, as this is just an example, I have no problems with merging it if that helps you.

**Review by Jarema — APPROVED** [review]
LGTM

**Comment by xoac** [comment]
> I meant that this is just a short example how library can be used :).

It's short and simple - exactly what I am looking for and I was able to use this in 2min when I wasn't able to install natscli in 2min 乁(⫑ᴥ⫒)ㄏ (no golang, not included with my distro. I don't download libraries that can't be updated automatically). I am not saying that natscli is bad or sth - but I use rust on daily basic and this is just simpler for me. I guess for golang people it would be easier just go with natscli.

**Pull request merged**
