### PR TITLE
Add publish to jetstream with ack

### PR DESCRIPTION
**Pull request by Jarema**
Addressing #215

### CODE REVIEW

**Comment by Jarema** [comment]
@spacejam @derekcollison  self-review:

This has to be improved, as now when you send message to subject not attached to any stream, it will hang indefinitely, while we should return error informing that there is no stream that can respond (like Go client does).

Am I right?

**Comment by Jarema** [comment]
After some investigation: it seems that Rust library is not checking headers after publishing message, so it doesn't catch the `503` status.

**Comment by derekcollison** [comment]
All clients should roughly mirror the Go client which in general tends to be our reference client. We will need to make sure that is the case.

**Comment by Jarema** [comment]
Converting to draft. After revisiting, it needs more work and though.

**Pull request closed without merging**
