### PR TITLE
Allow async and sync nats to compile on MIPS and PowerPC

### PR DESCRIPTION
**Pull request by protochron**
Now that nats.rs depends on a version of rustls that includes the latest version of ring, it can now be compiled to run on additional types of CPU architectures.

Specifically this converts all uses of `AtomicU64` to use the type provided by the `portable-atomic` crate, which uses the native version of `AtomicU64` on all architectures except MIPS and PowerPC where that type isn't supported.

I went ahead and updated sync nats with the latest version of rustls which inflated the size and scope of this PR beyond just swapping out the AtomicU64 implementation.

### CODE REVIEW

**Comment by protochron** [comment]
I just ran across https://github.com/taiki-e/portable-atomic which might be better because it would provide support for even more architectures

**Comment by Jarema** [comment]
Thanks for this contribution!

I checked briefly the `portable-atomics` and it looks good, with minimal depedencies.
Will bench it soon and review it.
This is nice timing too, as we're now investigating options to support more architectures.

**Comment by paolobarbolini** [comment]
Going by the popularity I'd also consider crossbeam-utils [`crossbeam_utils::atomic::AtomicCell`](https://docs.rs/crossbeam-utils/0.8/crossbeam_utils/atomic/struct.AtomicCell.html)

**Comment by Jarema** [comment]
@protochron I would like this to be merged, however, it would be good to check the crossbeam_utils against the less know crate :).

**Comment by protochron** [comment]
@Jarema I think using crossbeam_utils directly would be a much more substantial change to the code. I'd have add some directives around the AtomicU64 imports and calls where we need AtomicU64s to using an AtomicCell instead which is effectively what the portable-atomics crate does already. Also the owner of the portable-atomics crate is one of the owners of crossbeam-utils is the person who wrote the portable-atomics crate, so I'm pretty sure they've done a better job of implementing atomics on these platforms than I will :D

**Comment by Jarema** [comment]
Ok, point taken @thomastaylor312 and @protochron  :). Those are really strong arguments. 

Let's stick to portable atomics.
I will review it shortly.

**Comment by Jarema** [comment]
@protochron I would like to merge this before doing a release, so a kind nudge to fix conflicts :).

**Comment by protochron** [comment]
Sorry about that! Just synced main and resolved the conflicts

**Review by Jarema — APPROVED** [review]
LGTM!

**Pull request merged**
