### PR TITLE
Setup cargo deny to check licenses

### PR DESCRIPTION
**Pull request by corbinu**
Setup cargo deny and add to CI workflow to resolve issue #698

### CODE REVIEW

**Comment by Jarema** [comment]
Thanks for the contribution!

That looks good, but needs #704 merged, as `nats-server` crate was missing license.

**Comment by Jarema** [comment]
@corbinu please resolve the conficts and we're ready to merge.

**Review by caspervonb — APPROVED** [review]
lgtm

**Comment by matthiasbeyer** [comment]
@corbinu and @caspervonb - I found this when investigating the issue of this library using `ring`, which has an unclear license.

The commit added in this PR whitelists the `ring` crate and overrides it as `"MIT AND ISC AND OpenSSL"`. I would like to understand how this was justified and whether you contacted a Laywer about that matter. If so, please point me to the relevant resource to draw my own conclusions on that matter.

**Pull request merged**
