### PR TITLE
Upgrade rustls to v0.23 and add support for aws-lc-rs

### PR DESCRIPTION
**Pull request by paolobarbolini**
Depends on https://github.com/rustls/tokio-rustls/pull/59

### CODE REVIEW

**Comment by paolobarbolini** [comment]
Thinking more about this the FIPS feature may not make sense because nkeys for example uses crypto from RustCrypto, which isn't FIPS certified https://crates.io/crates/nkeys/0.4.0/dependencies

**Comment by Callum-A** [comment]
Hey is there any plans to merge this, there's a security advisory that depends on this version bump.  

https://github.com/advisories/GHSA-6g7w-8wpp-frhj

**Comment by paolobarbolini** [comment]
> Hey is there any plans to merge this, there's a security advisory that depends on this version bump.
> 
> [GHSA-6g7w-8wpp-frhj](https://github.com/advisories/GHSA-6g7w-8wpp-frhj)

To be fair this is not true. The patch was backported to previous versions of `rustls`. `cargo update -p rustls` is enough to fix the issue.

**Comment by Jarema** [comment]
@Callum-A we are planning to merge this soon.

**Comment by Callum-A** [comment]
That's all @paolobarbolini is correct. Ty for the info, the advisory we received on our end has been resolved :)

**Comment by Jarema** [comment]
I wonder if it makes sense to default to `ring`, as that seems to be pain-free path for Windows users?
Though of course it's going opposite direction than the rustls crate itself...

**Comment by jadamcrain** [comment]
Defaulting to ring is a good idea IMO. There's a lot of hate and discontent over in the rustls issue tracker ATM about their choice to default to aws-lc-rs.

Personally, I'm excited to have aws-lc-rs as an option because it's being maintained by a large company and not a solo maintainer, but the build issues are real.

**Comment by paolobarbolini** [comment]
Fixed

**Comment by Jarema** [comment]
@paolobarbolini thanks!
Though I think we still need nasm in CI :)

**Comment by paolobarbolini** [comment]
I've switched the tests back to `ring`.

**Review by Jarema — APPROVED** [review]
LGTM!

**Pull request merged**
