### PR TITLE
Fix a couple of minor things

### PR DESCRIPTION
**Pull request by caspervonb**

### CODE REVIEW

**Comment by Jarema** [comment]
@caspervonb  ditched the idea of alias?

**Comment by caspervonb** [comment]
> @caspervonb ditched the idea of alias?

Yeah considering this a fairly obvious bug/mistake and this just shipped recently I'm feeling okay with doing it in a patch release if you concur.

**Comment by Jarema** [comment]
I would be angry If I bumped patch version and got code red in IDE. Even if just because of typo.

Let's alias. We will get rid of it soon anyway with rewrite.

**Review by Jarema — APPROVED** [review]
LGTM

**Pull request merged**
