### PR TITLE
set TCP_NODELAY

### PR DESCRIPTION
**Pull request by andy-k**

### CODE REVIEW

**Comment by spacejam** [comment]
@andy-k have you measured this to improve long tail latencies on a real workload? Many nats workloads are throughput oriented and this just adds some complexity that people who tune TCP at the system level may not anticipate.

**Review by spacejam — CHANGES_REQUESTED** [review]
have you measured this additional complexity to improve a real workload?

**Comment by andy-k** [comment]
Thanks for the review.
It's unclear what change is requested.

I'm not familiar with how to tune TCP at the system level to enable TCP_NODELAY on all sockets.

I now understand from your comments that real nats workloads are throughput oriented, and my latency-sensitive workload is therefore not a real workload.

I had a quick look at some other libraries linked from https://nats.io/download/, and found that they are tuned to handle non-real workloads such as mine:
- https://github.com/nats-io/nats.go doesn't explicitly set TCP_NODELAY, but that's because [the default is true in Go](https://golang.org/pkg/net/#TCPConn.SetNoDelay).
- https://github.com/nats-io/nats.c/blob/cadc5e4827a838df05f69392a60ff4f7cc5b37f4/src/comsock.c#L58-L60
- https://github.com/nats-io/nats.cr/blob/aa4979137c5d98fa56baeaae05bd2a1837a46045/src/nats/connection.cr#L78
- https://github.com/nats-io/nats.js/blob/c65bd66c52c6c0d4a1b15456df46e59e230ed811/lib/nats.js#L940
- https://github.com/nats-io/nats-pure.rb/blob/0116743f866b7be90bd729596bf4034d3339a01c/lib/nats/io/client.rb#L1438
- https://github.com/DawnAngel/lua-nats/blob/980da7ac8f4c15541d114bf0cd17beff2666d9b7/src/nats.lua#L35
- https://github.com/Gr1N/nats-python/blob/d3601174b72a5dcdafc2bbb7b0bdeea775e79e5e/pynats/client.py#L168

However, I'd prefer not to have to rewrite my application into a different language.

Is there a workaround?

**Comment by spacejam** [comment]
It seems that this issue relates to some sort of desired performance characteristic. How does this change impact the workloads you have in mind?

**Comment by spacejam** [comment]
in #85 @saabye-io gathered some compelling metrics showing that this is likely to show a strong positive impact. Now that we have actual evidence that this change could improve things, I'm comfortable merging it

**Comment by spacejam** [comment]
0.9.3 is now published which includes this change. I would be interested in seeing any additional metrics that demonstrate its impacts for various workloads.

**Pull request merged**
