### PR TITLE
chore: fix sync TLS authentication for EC keys

### PR DESCRIPTION
**Pull request by sp-angel**
Fixes issue https://github.com/nats-io/nats.rs/issues/1126

### CODE REVIEW

**Comment by sp-angel** [comment]
Test failing with stable/ubuntu that cropped up seems related to latest [1.73.0](https://github.com/rust-lang/rust-clippy/issues/11390). 

Can change the code to pass, but that's not related to this change.

**Comment by Jarema** [comment]
Thanks for the PR!

Will be green after #113  is merged.

**Comment by sp-angel** [comment]
Nice, seems all tests passed now :smile:

**Comment by sp-angel** [comment]
hey, I'd love to get this merged. Is there anything pending I could help?

**Review by robjtede — APPROVED** [review]
@Jarema Bump +1. We'd like to have this change please.

**Review by Jarema — APPROVED** [review]
LGTM!

Thanks for your contribution!

**Pull request merged**
