### PR TITLE
Add Context::get_consumer_from_stream

### PR DESCRIPTION
**Pull request by Jarema**
Derek asked about a direct method to avoid one additional call to the server.
Useful mostly when you get very few Consumers and latency is critical.

Signed-off-by: Tomasz Pietrek <tomasz@nats.io>

### CODE REVIEW

**Comment by caspervonb** [comment]
The API is already fluid, is this really measurable?

**Review by caspervonb — CHANGES_REQUESTED** [review]
The API is already fluid, is this really measurable? If so, these could live in a `ConsumerExt` trait or something along those lines.

Lets discuss this more on our next sync call (pushing to next release).

**Comment by Jarema** [comment]
Agree, this should be an ConsumerExt

**Comment by Jarema** [comment]
After recent changes, all clients will implement this and it should be available without Ext.

**Pull request merged**
