### PR TITLE
Use `Duration` in a few more places

### PR DESCRIPTION
**Pull request by paolobarbolini**
Depends on #1037

### CODE REVIEW

**Comment by paolobarbolini** [comment]
Ah right. I forgot the default serializer implementation is useless, and serde_nanos doesn't support `Option`s

**Comment by caspervonb** [comment]
> serde_nanos doesn't support Options

Did add support for Option a while ago, which case is failing?
Could you file an issue or PR against https://github.com/caspervonb/serde_nanos ?

**Comment by paolobarbolini** [comment]
Ah I didn't realize how the API worked. I assumed it was like how `time` does it by having you go through a different module. I'll update the PR

**Review by caspervonb — APPROVED** [review]

**Comment by Jarema** [comment]
@paolobarbolini Judging by commits in the PR, I guess some gremlin sneaked while rebasing the branch ;).

**Comment by paolobarbolini** [comment]
Fixed

**Review by Jarema — APPROVED** [review]
LGTM!

**Pull request merged**
