### PR TITLE
Client rewrite

### PR DESCRIPTION
**Pull request by Jarema**
This PR is a Work in Progress for a client rewrite.

Goal of this PR is to have stable, performant, well tested Core NATS capabilities with most features in.

This PR does not and will not contain JetStream, KV, ObjectStore. 
Those will be added after this is merged.

This PR also changes the structure of the repo to support both old and new client, at least until new Client has feature parity with sync client.

- [x] Publish
- [x] Subscribe
- [ ] Unsubscribe (@caspervonb)
- [x] Make `Client` clonable
- [ ] Reconnections (@caspervonb)
- [x] TLS
- [x] client initiated flushes
- [ ] no responders
- [ ] lame duck mode
- [ ] async error callbacks/handling
- [x] test coverage
- [ ] bencharks
- [ ] add flush once in a while

### CODE REVIEW

**Comment by QuentinPerez** [comment]
👋 
First of all, thanks for your work.
I needed this implementation for a project with a lot of subscriptions, I took your work and adapted it a bit.
So don't hesitate to pick whatever you want or if you have feedbacks 👍  

https://github.com/znly/nats.rs/commits/async-rewrite

**Comment by Jarema** [comment]
@QuentinPerez thanks for the info and your work!
I will look into it.

**Comment by Jarema** [comment]
all pending features will be issued against main.

**Review by derekcollison — APPROVED** [review]
LGTM

**Pull request merged**
